# Generated by Django 3.2.7 on 2024-04-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0004_station_regtable_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_regtable',
            name='cpassword',
        ),
    ]
