# Generated by Django 3.2.7 on 2024-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0005_remove_station_regtable_cpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='cam1tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='cam2tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='cam3tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
    ]
